#  LINH WEB SERVER
##############################################

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:  
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
     
server:
  port: 1111   
  
  
spring:
  application:
    name: hello-service
  thymeleaf:
    cached: false     
    prefix: classpath:/web-views/
  datasource:
    url: jdbc:mysql://localhost:3306/user_model
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            #scripts:
              #action: create
              #create-target: ipos_contacts.sql
              
           
hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  show_sql: true