#  LINH WEB SERVER
##############################################

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:  
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
     
server:
  port: 8080   
  
  
spring:
  application:
    name: elasticsearch
  thymeleaf:
    cached: false   
    
    
    
    
#    
#logging:
#  file: logs/log.out
#  pattern:
#    file: "%d %-5level [%thread] %logger : %msg%n"
#  level:
#    #org.springframework: ERROR
#    hello: DEBUG 
#    
    
    
      
    #prefix: classpath:/web-views/
#  datasource:
#    url: jdbc:mysql://localhost:3306/user_model
#    driverClassName: com.mysql.jdbc.Driver
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            #scripts:
#              #action: create
#              #create-target: ipos_contacts.sql
#              
#           
#hibernate:
#  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  show_sql: true